#!/usr/bin/env lua
local isWin=string.find(string.lower(os.getenv('OS') or 'nil'),'windows')~=nil
if isWin then
	package.path =os.getenv('HOMEDRIVE')..os.getenv('HOMEPATH').."/bin/?.lua" .. ";"..package.path 
	if os.getenv('HOME') then
		package.path =os.getenv('HOME').."/bin/?.lua" .. ";"..package.path 
	end
else
	package.path =os.getenv('HOME').."/bin/?.lua" .. ";"..package.path 
end
if _VERSION=='Lua 5.2' then
	require("mylib52")
else
	require("mylib")
end

local original = require'fzy_lua'

local scriptPrefix
if true then
	-- modify the scriptPrefix as you want.
	-- to use taesooLib without python3 dependency
	if os.isWindows() then
		-- autodetect using the current directory name
		local curDir=os.currentDirectory()
		curDir=os.toWindowsFileName(curDir)
		if select(1, string.find(curDir,'sample_python')) then
			local s,e=string.find(curDir,'sample_python')
			scriptPrefix= 'cd '..curDir:sub(1,e)..'/work;./nopython '
		elseif select(1, string.find(curDir,'sample_physX')) then
			local s,e=string.find(curDir,'sample_physX')
			scriptPrefix= 'cd '..curDir:sub(1,e)..'/work;./nopython '
		elseif select(1, string.find(curDir, 'taesooLib')) then
			local s,e=string.find(curDir,'taesooLib')
			scriptPrefix= 'cd '..curDir:sub(1,e)..'/work;./classification '
			--scriptPrefix= 'cd '..curDir:sub(1,e)..'/work;python runLua.py '
		else
			-- if failed to use the home_path directory name, fallback 
			scriptPrefix= 'cd '..curDir..'/sample_python/work;./nopython '
		end
	else
		-- autodetect using the current directory name
		if select(1, string.find(os.currentDirectory(),'sample_python')) then
			local s,e=string.find(os.currentDirectory(),'sample_python')
			scriptPrefix= 'cd '..os.currentDirectory():sub(1,e)..'/work;./nopython '
		elseif select(1, string.find(os.currentDirectory(),'sample_physX')) then
			local s,e=string.find(os.currentDirectory(),'sample_physX')
			scriptPrefix= 'cd '..os.currentDirectory():sub(1,e)..'/work;./nopython '
		elseif select(1, string.find(os.currentDirectory(), 'taesooLib')) then
			local s,e=string.find(os.currentDirectory(),'taesooLib')
			scriptPrefix= 'cd '..os.currentDirectory():sub(1,e)..'/work;./classification '
			--scriptPrefix= 'cd '..os.currentDirectory():sub(1,e)..'/work;python runLua.py '
		else
			-- if failed to use the current directory name, fallback 
			scriptPrefix= 'cd '..os.home_path()..'/sample_python/work;./nopython '
		end
	end

	-- scriptPrefix examples:
	-- for wsl users having openGL-related problems.
	--scriptPrefix= 'cd ~/sample_physX/work;GALLIUM_DRIVER=llvmpipe ./nopython '

	-- to use taesooLib with PhysX simulator and without python3 dependency
	--scriptPrefix= 'cd ~/sample_physX/work;./nopython '

	-- to use taesooLib with PhysX simulator and with python3 dependency
	--scriptPrefix= 'cd ~/sample_physX/work;python3 test_sample_python.py '
	--scriptPrefix= 'cd '..os.home_path()..'\\sample_torch\\work;.\\release\\nopython '

	-- to use cgdb. you first need to "make debugexe" and "make debug"
	--scriptPrefix= 'cd ~/sample_python/work;cgdb -- --args ./nopython_d '
	--scriptPrefix= 'cd ~/sample_python/work;cgdb -- --args python3 test_sample_python.py '
	
	-- to use lldb (mac). you first need to "make debugexe"
	--scriptPrefix= 'cd ~/sample_python/work;lldb -- ./nopython_d '
end


if os.isWindows() then
	local execute2_original=os.execute2
	function os.execute2(cmd)
		local cmdsep=string.tokenize(cmd,';')
		execute2_original(unpack(cmdsep))
	end
end

function filter(fzy, needle, lines)
  results = {}
  for i, line in ipairs(lines) do
    if fzy.has_match(needle, line) then
      local positions = fzy.positions(needle, line)
      table.insert(results, {line, positions})
    end
  end
  return results
end

function lsFiles(wildcard)
	if os.isWindows() then
		local i, t, popen = 0, {}, io.popen
		for filename in popen('dir "'..wildcard..'" /b'):lines() do
			i = i + 1
			t[i] = filename
		end
		return t
	else
		local files=string.lines(os.capture('ls -1 '..wildcard, true))
		files[#files]=nil
		return files
	end
end

function main()
	if scriptPrefix==nil then
		for i, v in ipairs(priority) do
			if #lsFiles(v[2])>0 then
				scriptPrefix=v[1]
				break
			end
		end
		if scriptPrefix==nil then
			print('Error! cannot find libmainlib*.so. Please build sample_physX or sample_python.')
			return
		end
	end



	local pattern
	if arg[1] and arg[1]~='-p' then
		pattern=arg[1]
		if os.isWindows() then
		if pattern:sub(1,2)==".\\" then
			pattern=pattern:sub(3)
		end
	end

	end
	if not pattern then
		local tl=os.processFileName(arg[0])
		print('usage: '..tl..' wrlv')
		print('current setting: '..scriptPrefix..' path_to_wrlv.lua')
		return
	end

	if pattern:sub(1,1)=='/' then
		execute(scriptPrefix, pattern)
		return
	end
	local files= lsFiles('*.lua')
	local res=filter(original, pattern, files)

	if #res==0 then
		files= lsFiles('*.py')
		res=filter(original, pattern, files)
	end

	local succeeded=false
	if #res==1 then
		succeeded=true
	elseif #res==0 then
		print('no matches found in "ls"')
	else
		print('multiple matches:')
		printTable(res)

		-- still ok.
		-- search for the best one
		local MIN_DIST=100000
		local argmin=1

		for i, v in ipairs(res) do
			--local editDist=v[2][1]-1
			local editDist=0 -- ignore prefix distance
			for j=2, #v[2] do
				editDist=editDist+v[2][j]-v[2][j-1]-1
			end
			editDist=editDist+(v[1]:len()-v[2][#v[2]] )*0.001 -- postfix distance uses a low-weight
			editDist=editDist+(v[2][1])*0.001 -- prefix distance uses a low-weight
			
			if editDist<MIN_DIST then
				argmin=i
				MIN_DIST=editDist
			end
		end
		res[1]=res[argmin]

		succeeded=true
	end
	if succeeded then
		local currDir=os.currentDirectory()
		execute(scriptPrefix,currDir..'/'..res[1][1])
	else
		print('searching using "git ls-files"...')
		dofile(os.home_path()..'/bin/gitv')

		local fn=nonInteractiveChoose({arg[1]})
		if #fn==1 then
			local currDir=os.currentDirectory()
			execute(scriptPrefix,currDir..'/'..fn[1][1])
		else
			printTable(fn)
			print('Error! cannot find '..arg[1].. ' in both "ls" and "git ls-files"!')
		end
	end
end

function execute(scriptPrefix, fn)
	if fn:sub(-3)==".py" then
		print('python3 "'..fn..'"')
		if os.isWindows() then
			os.execute('python3 "' ..os.toWindowsFileName(fn)..'"')
		else
			os.execute('python3 "'..fn..'"')
		end
		return
	end
	print(scriptPrefix..'"'..fn..'"')
	if arg[2] then
		local currDir=os.currentDirectory()
		if os.isWindows() then
			os.execute2(scriptPrefix..'--dostring:arg=\\"'.. currDir..':'..arg[2]..'\\" "' ..os.toWindowsFileName(fn)..'"')
		else
			os.execute2(scriptPrefix..'--dostring:arg=\\"'..currDir..':'..arg[2]..'\\" "' ..fn..'"')
		end
	else
		if os.isWindows() then
			os.execute2(scriptPrefix..'"'..os.toWindowsFileName(fn)..'"')
		else
			os.execute2(scriptPrefix ..'"'..fn..'"')
		end
	end
end
main()
